/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    'admin-dashboard': AdminDashboard;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'admin-dashboard': AdminDashboardSelect<false> | AdminDashboardSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  heroImage?: (number | null) | Media;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaText?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            heading?: string | null;
            text?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            /**
             * Titre optionnel affiché au-dessus du document
             */
            title?: string | null;
            /**
             * Collez l'URL complète du document Google Docs (doit être partagé en lecture publique). Ex: https://docs.google.com/document/d/DOCUMENT_ID/edit
             */
            googleDocsUrl: string;
            /**
             * Hauteur de l'iframe en pixels
             */
            height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'googleDocsEmbed';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  publishedDate?: string | null;
  author?: (number | null) | User;
  featuredImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?:
    | {
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        googleDocsEmbed?:
          | T
          | {
              title?: T;
              googleDocsUrl?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Logo affiché dans la navbar et au-dessus du titre principal
   */
  logo?: (number | null) | Media;
  /**
   * Image de fond pour la section principale (hero)
   */
  heroBackground?: (number | null) | Media;
  heroTitle: string;
  /**
   * Ce mot apparaîtra en doré dans le titre
   */
  heroTitleAccent?: string | null;
  heroSubtitle?: string | null;
  heroDescription?: string | null;
  heroPrimaryButtonText?: string | null;
  heroPrimaryButtonUrl?: string | null;
  heroSecondaryButtonText?: string | null;
  heroSecondaryButtonUrl?: string | null;
  serversTitle?: string | null;
  /**
   * Nom de l'icône Lucide (ex: Swords, Server, Gamepad2)
   */
  serversIcon?: string | null;
  servers?:
    | {
        name: string;
        mode: string;
        description?: string | null;
        maxPlayers?: number | null;
        map?: string | null;
        /**
         * Adresse IP du serveur (ex: 51.75.68.111)
         */
        ip?: string | null;
        /**
         * Port de connexion au jeu
         */
        gamePort?: number | null;
        /**
         * Port pour interroger le serveur (Steam Query / A2S). Généralement gamePort + 1 ou un port dédié.
         */
        queryPort?: number | null;
        /**
         * Statut manuel si la requête A2S échoue
         */
        isOnline?: boolean | null;
        id?: string | null;
      }[]
    | null;
  isPresentationVisible?: boolean | null;
  presentationTitle?: string | null;
  /**
   * Nom de l'icône Lucide pour le titre (ex: Video, Play, Film)
   */
  presentationIcon?: string | null;
  presentationVideoTitle?: string | null;
  /**
   * Collez l'URL d'intégration de la vidéo (ex: YouTube embed URL https://www.youtube.com/embed/VIDEO_ID)
   */
  presentationVideoLink?: string | null;
  isFeaturesVisible?: boolean | null;
  featuresTitle?: string | null;
  /**
   * Nom de l'icône Lucide pour le titre (ex: Star, Award, Sparkles)
   */
  featuresIcon?: string | null;
  features?:
    | {
        /**
         * Nom de l'icône Lucide (ex: Medal, Target, ClipboardList, Shield, Users, Gamepad2)
         */
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  isNewsVisible?: boolean | null;
  newsTitle?: string | null;
  /**
   * Nom de l'icône Lucide (ex: Newspaper, Bell, Megaphone)
   */
  newsIcon?: string | null;
  isCtaVisible?: boolean | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaButtonText?: string | null;
  ctaButtonUrl?: string | null;
  discordUrl?: string | null;
  youtubeUrl?: string | null;
  twitterUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Gérez les liens affichés dans la barre de navigation
   */
  links?:
    | {
        label: string;
        type: 'internal' | 'external' | 'anchor';
        page?: (number | null) | Page;
        /**
         * URL complète pour externe, ou #section pour ancre
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Affiche le lien comme un bouton (ex: Discord)
         */
        isHighlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL du serveur Discord (utilisé pour le bouton Discord)
   */
  discordUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-dashboard".
 */
export interface AdminDashboard {
  id: number;
  /**
   * Ajoutez des cartes de lien affichées sous le dashboard admin. Utilisez le bouton pour ajouter un nouveau lien.
   */
  links?:
    | {
        title: string;
        description: string;
        /**
         * Ex: https://monitor.lif-arma.com
         */
        url: string;
        /**
         * Emoji ou texte court (ex: 📊, 🖥️, DB)
         */
        icon: string;
        /**
         * Format hexadécimal, ex: #4a7c23
         */
        color: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  logo?: T;
  heroBackground?: T;
  heroTitle?: T;
  heroTitleAccent?: T;
  heroSubtitle?: T;
  heroDescription?: T;
  heroPrimaryButtonText?: T;
  heroPrimaryButtonUrl?: T;
  heroSecondaryButtonText?: T;
  heroSecondaryButtonUrl?: T;
  serversTitle?: T;
  serversIcon?: T;
  servers?:
    | T
    | {
        name?: T;
        mode?: T;
        description?: T;
        maxPlayers?: T;
        map?: T;
        ip?: T;
        gamePort?: T;
        queryPort?: T;
        isOnline?: T;
        id?: T;
      };
  isPresentationVisible?: T;
  presentationTitle?: T;
  presentationIcon?: T;
  presentationVideoTitle?: T;
  presentationVideoLink?: T;
  isFeaturesVisible?: T;
  featuresTitle?: T;
  featuresIcon?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  isNewsVisible?: T;
  newsTitle?: T;
  newsIcon?: T;
  isCtaVisible?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  ctaButtonText?: T;
  ctaButtonUrl?: T;
  discordUrl?: T;
  youtubeUrl?: T;
  twitterUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        isHighlighted?: T;
        id?: T;
      };
  discordUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-dashboard_select".
 */
export interface AdminDashboardSelect<T extends boolean = true> {
  links?:
    | T
    | {
        title?: T;
        description?: T;
        url?: T;
        icon?: T;
        color?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}